#!/bin/bash

# computer the dir of this script
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Deploy the filepicker files
${DIR}/deploy

# register the filepicker
if [[ $? -eq 0 ]]; then
	echo -e "# OmeroFilePicker \nMoodleQuickForm::registerElementType('omerofilepicker', \"\$CFG->libdir/form/omerofilepicker.php\", 'MoodleQuickForm_omerofilepicker');" >> ${MOODLE_WWW}/lib/formslib.php
fi